### ISSUE TITLE
CK2 says CanHibernate=true but it's false :-)

### ISSUE THREAD

**Issue by rworkman** [ConsoleKit2/ConsoleKit2#55]
Trying out upower-0.99.3 here, and after a rebuild of the various xfce components that link libupower-glib, all is well with one exception. The logout dialog offers the expected options (Logout, Reboot, Shutdown, Suspend) plus an unexpected Hibernate. The system is perfectly capable of hibernating aside from one major problem: I have no swap space (yes, that is intentional). 

> $ xfce4-power-manager --dump
>        Xfce power manager version 1.4.4
> With policykit support
> With network manager support
> Can suspend: True
> Can hibernate: True
> Authorized to suspend: True
> Authorized to hibernate: True
> Authorized to shutdown: True
> Has battery: True
> Has brightness panel: True
> Has power button: True
> Has hibernate button: True
> Has sleep button: True
> Has LID: True

It seems that xfpm gets CanHibernate from CK2, so let's make sure:

> $ dbus-send --system --dest=org.freedesktop.ConsoleKit \
> --type=method_call --print-reply --reply-timeout=2000 \
> /org/freedesktop/ConsoleKit/Manager \
> org.freedesktop.ConsoleKit.Manager.CanHibernate
> method return time=1450039272.192999 sender=:1.0 -> destination=:1.39 serial=251 reply_serial=2
>   string "yes"

If I click the "Hibernate" option in the logout dialog, the system attempts to hibernate but then bails out when it realizes that there's no swap space available.

So who should check to see if hibernation is actually possible? Is this something that CK2 should do, or xfpm, or some other suggestion?

**Comment by rworkman** [comment]
upower-0.9.23 had some code to check currently used swap and needed space for hibernate - I guess the question now is where that code (or similar) should go? CK2 or xfpm? It will be platform specific too, I suppose :/

**Comment by udeved** [comment]
This is interesting.
I have experimented with upower-0.99 too, and wanted to see if I can replace upower-0.9.23 with the current one.

What you describe seems to also happen with lxqt, where hibernate is greyed out, but xfce and kde5 appear to be solidly working with 0.99.

I do have a swap partition.

**Comment by rworkman** [comment]
Looking at lxsession 0.5.2, it appears to use CK only for shutdown and reboot, while either upower or systemd is used for suspend/hibernate, sooo... are you using systemd there, or maybe a later lxsession? It doesn't look like suspend/hibernate would work at all with lxsession if you upower-0.99.3 unless systemd is installed.

**Comment by udeved** [comment]
No systemd here, openrc, ck2, and lxqt, not lxde.

**Comment by rworkman** [comment]
oh, hrm... well, I can't figure out how lxqt even decides whether to offer hibernate as an option, so no idea there. Maybe there's some qt-based abstraction backend that handles all of it, or maybe not. I haven't looked at any qt/kde-related code in six forevers, and today's not the day I plan to start again :-)

**Comment by udeved** [comment]
Don't bother, it just an experiment for me to determine, if we can make upower-0.99 default in our iso-profiles, or if we should handle it individually per profile.

**Comment by rworkman** [comment]
@EricKoegel, I'm pretty much incompetent with C, but this seems to work for me here with very limited testing. There are a couple of warnings during compilation though, so ultimately, this needs close scrutiny... Please review when you have time...

**Comment by EricKoegel** [comment]
Hey I pushed your commit to master and a tiny patch right after, thanks! Sorry it took so long to get to it.

**Comment by rworkman** [comment]
No worries - thanks for the fixup too!
The only hurdle now (for Slackware, at least) with moving to upower-0.99.3 is kde4. I found your patch for kde-workspace to use CK2 as power backend and backported it to kde4, but kde still doesn't know that it can suspend. It won't matter for the near term anyway, because we decided to stick with upower-0.9.23 for the next Slackware release, but kde has to work too. One of our other devs has some qt5/kde5 packages in a testing repo, so I'll try those and see what happens - I'll try not to bother you about it, but the kde codebase is an entirely different (and unfamiliar) beast to me...
